export const productItems = [
	{
		id: 1,
		company: "Vijay",
		category: "IronBox",
		name: "VA52 DLX Heavy weight",
		price: 100,
		image: require("../Images/Horizontal.jpeg"),
	},
	{
		id: 2,
		company: "Vijay",
		category: "IronBox",
		name: "VA52 Heavy weight",
		price: 150,
		image: require("../Images/Vertical.jpeg"),
	},

	{
		id: 3,
		company: "Vijay",
		category: "IronBox",
		name: "VA88 Heavy weight",
		price: 150,
		image: require("../Images/Vertical.jpeg"),
	},
	{
		id: 4,
		company: "Vijay",
		category: "IronBox",
		name: "VNA80 Dlx Heavy weight",
		price: 150,
		image: require("../Images/Vertical.jpeg"),
	},
	{
		id: 5,
		company: "Vijay",
		category: "IronBox",
		name: "SUPRA Dry Iron",
		price: 150,
		image: require("../Images/Vertical.jpeg"),
	},
	{
		id: 6,
		company: "Vijay",
		category: "IronBox",
		name: "Sophia Dry Iron",
		price: 150,
		image: require("../Images/Vertical.jpeg"),
	},
	{
		id: 7,
		company: "Vijay",
		category: "IronBox",
		name: "CUTE Dry Iron",
		price: 150,
		image: require("../Images/Vertical.jpeg"),
	},
	{
		id: 8,
		company: "Vijay",
		category: "Winter Products",
		name: "IMMERSION HEATER 1000W",
		price: 150,
		image: require("../Images/Vertical.jpeg"),
	},
	{
		id: 9,
		company: "Vijay",
		category: "Winter Products",
		name: "IMMERSION HEATER 1500W",
		price: 150,
		image: require("../Images/Vertical.jpeg"),
	},
	{
		id: 10,
		company: "Vijay",
		category: "Winter Products",
		name: "IMMERSION HEATER Dlx 1000W",
		price: 150,
		image: require("../Images/Vertical.jpeg"),
	},

	{
		id: 11,
		company: "Vijay",
		category: "Winter Products",
		name: "IMMERSION HEATER Dlx 1500W",
		price: 150,
		image: require("../Images/Vertical.jpeg"),
	},
];
